blueprint:
  name: Beoremote Halo Motion Sensor
  description: This blueprint will use active and sleep system events fired based on proximity as a motion sensor.
  domain: automation

  input:
    serial_number:
      name: Device Serial Number
      description: The serial number of the Bang & Olufsen Halo device.
      selector:
        text:

variables:
  serial_number: !input "serial_number"
  virtual_motion_sensor: "input_boolean.bang_olufsen_halo_motion_{{ serial_number | lower }}"

trigger:
  - platform: event
    event_type: bang_olufsen_halo_websocket_event_in
    event_data:
      event:
        type: system
        state: active
      serial: !input "serial_number"

  - platform: event
    event_type: bang_olufsen_halo_websocket_event_in
    event_data:
      event:
        type: system
        state: sleep
      serial: !input "serial_number"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.event.type == "system" and
                 trigger.event.data.event.state == "active" and
                 trigger.event.data.serial == serial_number }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ virtual_motion_sensor }}"

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.event.type == "system" and
                 trigger.event.data.event.state == "sleep" and
                 trigger.event.data.serial == serial_number }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ virtual_motion_sensor }}"