blueprint:
  name: Beoremote Halo Motion Sensor
  description: This blueprint will use active and sleep system events fired based on proximity as a motion sensor.
  domain: automation

  input:
    serial_number:
      name: Device Serial Number
      description: The serial number of the Beoremote Halo.
      selector:
        text:

variables:
  serial_number: !input "serial_number"
  virtual_motion_sensor: input_boolean.bang_olufsen_halo_motion_{{ serial_number | lower }}

trigger:
  - platform: event
    event_type: bang_olufsen_halo_websocket_event_in
    event_data:
      event:
        type: system
        state: active
      serial: !input "serial_number"

  - platform: event
    event_type: bang_olufsen_halo_websocket_event_in
    event_data:
      event:
        type: system
        state: sleep
      serial: !input "serial_number"

action:
  - choose:
      - conditions:
          - condition: trigger
            platform: event
            event_type: bang_olufsen_halo_websocket_event_in
            event_data:
              event:
                type: system
                state: active
              serial: !input "serial_number"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ virtual_motion_sensor }}"

      - conditions:
          - condition: trigger
            platform: event
            event_type: bang_olufsen_halo_websocket_event_in
            event_data:
              event:
                type: system
                state: sleep
              serial: !input "serial_number"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ virtual_motion_sensor }}"

# Create the input_boolean if it doesn't exist
  - service: input_boolean.create
    data:
      name: "Bang & Olufsen Halo Motion {{ serial_number }}"
      id: "{{ virtual_motion_sensor.split('.')[-1] }}"